version: '3'
services:
  django_postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
  django_redis:
    image: redis
    ports:
     - 6379:6379
  auction_system:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_CACHE_BACKEND=${CELERY_CACHE_BACKEND}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - django_postgres
  celery_worker:
    build: .
    command: sh -c "celery -A core worker -l INFO"
    volumes:
      - .:/code
    depends_on:
      - django_postgres
      - django_redis
      - auction_system
    environment:
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_CACHE_BACKEND=${CELERY_CACHE_BACKEND}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}


volumes:
  postgres_data:
