# Generated by Django 5.0 on 2023-12-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_product_description_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='minimum_bids',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
