# Generated by Django 5.0 on 2024-01-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Sold', 'SOLD'), ('Live', 'LIVE'), ('Inactive', 'INACTIVE')], default='INACTIVE', max_length=15),
            preserve_default=False,
        ),
    ]
