# Generated by Django 5.0 on 2024-01-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_remove_product_is_sold_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('sold', 'SOLD'), ('live', 'LIVE'), ('inactive', 'INACTIVE')], max_length=15),
        ),
    ]
