# Generated by Django 5.0 on 2024-01-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('inactive', 'INACTIVE'), ('live', 'LIVE'), ('closed', 'CLOSED')], default='pending', max_length=10),
        ),
    ]
