# Generated by Django 5.0 on 2024-01-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_alter_auction_status'),
        ('users', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('buyer', 'product')},
        ),
    ]
