# Generated by Django 5.0 on 2024-01-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_alter_bid_options_alter_bid_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='minimum_bids',
        ),
    ]
