# Generated by Django 5.0 on 2024-01-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_remove_auction_minimum_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test_field',
            field=models.IntegerField(default=0),
        ),
    ]
